stages:
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      name: "Publish to PyPi"
      language: python
      python: '3.7'
      install:
        - pip install -r test-requirements.txt
      deploy:
        provider: pypi
        user: AuHau-deploy
        distributions: sdist bdist_wheel
        skip_existing: true
        password:
          secure: jFzpBrVs69oMM/Ig16Q2pdo9ihK8330fpkF8wAdKq4O+nuNB7AntORjxFUh0PBvEwkfvvwML7HMnvlP8i8IMTaJoPvPYqAJYbNrUiG1SZj3AkufG6fyJ9LH8xU1iL5WB0MKjXDqcRGx+prjwp6HJkuYcgKYm8Mi5g8ydy7o+GtF2TYIWlfi7EzpkvIJJADxQvF5qUmKubz3AcIdfVQSjKiw4u30HIKHxEkqs6yDetNffTLz5MGiUTxkGIvgy7LsjTCwR92iDqNUZJdAG6lt3Zlu5T+mdh90ezk/AF7m6GMHmx+A77cnYPyblTaLdKmHGEmAgQeTdkqIi/bMQnf6hw4K2ntuqyQVeRfps4e5mEqs0jCYAQ+SNP5oMT0PS/D6faq930Si2Zdn2SVHi+S1n6FyH4Xh3rtn1/cymD5YhM02LeFgfTummHPI3dW8L1UZXD5SIRPvWRPiBqs5DjMFzWKZLgq7miMZrlu6b56rtI9FwryPXlvx9q6lN4tK+fG9XqYkEF5qmSurefTLxOeNm1wu+GBUr+hSPkY4eJOj3f7gzBPGWqruBMawFFY8ZS/CHCoBwHCWfkNxI594p0xUe0Hlcq0n5IrlKMmliTJfGruzVloP013AhpeeoOH5bImSeH6jShVgSdsHiva9GAetqnNK3aBKO2d3eKcbKljxel1U=
    - stage: deploy
      name: "Publish documentation"
      language: python
      python: '3.7'
      install:
        - pip install -r test-requirements.txt
      script:
        - git config user.name "Adam Uhlir";
        - git config user.email "hello@adam-uhlir.me";
        - git remote add gh-token "https://${GH_TOKEN}@github.com/AuHau/toggl-cli.git";
        - git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
        - mkdocs gh-deploy -v --clean --remote-name gh-token;
    - stage: deploy
      name: "Build and publish PEX to draft release"
      language: python
      python: '3.7'
      install:
        - pip install pex
      script:
        - pex --python=python3 -r requirements.txt -o ./build/gitrack.linux-x86_64 --platform linux-x86_64 -e gitrack.main gitrack setuptools
        - pex --python=python3 -r requirements.txt -o ./build/gitrack.macosx-10.6-x86_64 --platform macosx-10.6-x86_64 -e gitrack.main gitrack setuptools
      deploy:
        provider: releases
        skip_cleanup: true
        draft: true
        file:
          - ./build/gitrack.linux-x86_64
          - ./build/gitrack.macosx-10.6-x86_64