site_name: 'giTrack'
site_description: 'Zero-touch time tracking using Git'
site_author: 'Adam Uhlíř'
copyright: 'Copyright &copy; 2019 <a href="https://www.adam-uhlir.me">Adam Uhlíř</a>'

repo_name: 'auhau/gitrack'
repo_url: 'https://github.com/auhau/gitrack'
theme: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

google_analytics:
  - UA-69422360-4
  - auto



